#!/bin/sh

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Preserve the user's CWD so that relative paths are passed correctly to
#+ the underlying Python script.
# --authorized-address=209.12.74.162/32 --ebs-vol-size=50 --no-ganglia 
SPARK_EC2_DIR="$(dirname "$0")"

python -Wdefault "${SPARK_EC2_DIR}/spark_ec2.py" \
    --key-pair=analytics-sandbox -i ${HOME}/.ssh/analytics-sandbox.pem --profile=sandbox \
    --instance-type=m3.2xlarge --master-instance-type=m3.large --slaves=2 --hadoop-major-version=yarn \
    --region=us-west-2 --zone=us-west-2a \
    '--additional-tags=Owner:alexander.smirnov@mulesoft.com' --copy-aws-credentials --delete-groups \
    --spark-ec2-git-repo=https://github.com/alexsmirnov/spark-ec2 --spark-ec2-git-branch=branch-1.6 \
    --subnet-id=subnet-41eb6125 --vpc-id=vpc-9776fff3 --private-ips \
    "$@"
